version: '3'

services:
  app-a:
    build:
      context: ./app-a
    ports:
      - "5000:5000"
    depends_on:
      - app-b

  app-b:
    build:
      context: ./app-b
    ports:
      - "5001:5001"
