name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # O la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ec2_key.pem" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/Even_Odd_Distributed

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd Even_Odd_Distributed
            docker-compose down || true
            docker-compose build
            docker-compose up -d
          EOF
